images:
- name: kustomization-libplanet-seed
  newName: planetariumhq/libplanet-seed
  newTag: git-4d10b228048c03cc97a6fbb7fbfcd54d2bd1b21c
- name: kustomization-ninechronicles-headless
  newName: planetariumhq/ninechronicles-headless
  newTag: git-b5b23b956bba06e9407f7a20d7068a59245192cd
- name: kustomization-ninechronicles-snapshot
  newName: planetariumhq/ninechronicles-snapshot
  newTag: git-ffb78149efb29d893d4460b4f9a70260c6b340f3
- name: kustomization-ninechronicles-dataprovider
  newName: planetariumhq/ninechronicles-dataprovider
  newTag: git-8d2bb2702d585129f63bd488b71b72de5d6ccea6
- name: kustomization-ninechronicles-onboarding
  newName: planetariumhq/9c-onboarding
  newTag: git-36b2b5ca12e6bd059a81c17f92cb2803b38425bc
resources:
- explorer.yaml
- miner-1.yaml
- remote-headless-1.yaml
- data-provider.yaml
- data-provider-db.yaml
- onboarding-app.yaml
- onboarding-db.yaml
- onboarding-redis.yaml
- snapshot.yaml
- tcp-seed-deployment.yaml
